Update Dependencies
braintree/classlist pull request #17
Opened 2023-08-21 19:07 UTC by jplukarski

Makes the following major version updates (I verified that no breaking change should effect us):
- prettier
- eslint-plugin-prettier

Additionally, this includes updates submitted by dependabot in the following PRs:
- #15 
- #16 

For internal tracking -> 2912

2023-08-23 19:52 UTC, hollabaq86 requested changes
same feedback as what I left in the card-validator library re:CHANGELOG and Node version bump impacts

2023-08-23 19:52 UTC, hollabaq86 commented on CHANGELOG.md
> +- Dependency Updates:
let's clarify this to mention these are dev dependencies. Also don't forget the Typescript version bump

2023-08-24 00:21 UTC, oscarleonnogales approved these changes

2023-08-28 20:36 UTC, hollabaq86 approved these changes

2023-08-29 19:52 UTC, merged